filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /home/ubuntu/aggregation-service/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "34.242.78.131:5601"

output.elasticsearch:
  hosts: ["http://172.31.2.140:9200"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
